version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app # Hot-reload development (optional)

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    # volumes:
    #   - ./backend:/ # Hot-reload development (optional)
