import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SyncUserSession from "./syncusersession";
import Header from "../components/Header";
import { PublicEnvScript } from "next-runtime-env";
import ContactForm from "./savedetails";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Footer from "../components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <SyncUserSession />
        <head>
          <PublicEnvScript />
        </head>

        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <Header />
          <ContactForm></ContactForm>
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
